export const movesData = {
  "pound": { name: "Destructor", description: "Golpea al objetivo con las extremidades, la cola o similares." },
  "karate-chop": { name: "Golpe karate", description: "Da un golpe cortante. Suele ser crítico." },
  "double-slap": { name: "Doble bofetón", description: "Golpea al objetivo con las dos manos, es decir dos veces seguidas." },
  "comet-punch": { name: "Megapuño", description: "Puñetazo rápido que golpea al objetivo de dos a cinco veces seguidas." },
  "mega-punch": { name: "Megapuño", description: "Potente puñetazo concentrado que recae sobre el objetivo." },
  "pay-day": { name: "Monedazo", description: "El usuario ataca lanzando monedas, consiguiendo ganancias tras el combate." },
  "fire-punch": { name: "Puño fuego", description: "Puñetazo envuelto en fuego que puede causar quemaduras." },
  "ice-punch": { name: "Puño hielo", description: "Puñetazo helado que puede congelar al objetivo." },
  "thunder-punch": { name: "Puño trueno", description: "Puñetazo eléctrico que puede paralizar al objetivo." },
  "scratch": { name: "Arañazo", description: "Rápido arañazo con las garras o similares." },
  "vise-grip": { name: "Fuerza de garra", description: "Atenaza al objetivo y le inflige daño." },
  "guillotine": { name: "Guillotina", description: "Ataque cortante con grandes pinzas que fulmina al objetivo de un solo golpe si acierta." },
  "razor-wind": { name: "Viento cortante", description: "Primero se prepara y en el segundo turno ataca al oponente con ráfagas de viento cortante. Alta probabilidad de ser crítico." },
  "swords-dance": { name: "Danza de espadas", description: "Este frenético baile de combate eleva el espíritu y aumenta mucho el Ataque." },
  "cut": { name: "Corte", description: "Corta al objetivo con garras, guadañas o similares." },
  "gust": { name: "Ráfaga de aire", description: "Crea un tornado con las alas y lo lanza contra el objetivo." },
  "wing-attack": { name: "Ataque de ala", description: "Extiende totalmente sus majestuosas alas para golpear al objetivo con ellas." },
  "whirlwind": { name: "Remolino", description: "Se lleva al objetivo, que es cambiado por otro Pokémon. Si es uno salvaje, acaba el combate." },
  "defense-curl": { name: "Hacerse bolita", description: "Se enrosca para ocultar sus puntos débiles y aumentar la Defensa." },
  "double-kick": { name: "Doble patada", description: "Propina dos patadas seguidas, una con cada pie." },
  "slam": { name: "Golpazo", description: "Golpea con la cola o con lianas, por ejemplo, para causar daño al objetivo." },
  "vine-whip": { name: "Látigo cepa", description: "Azota al objetivo con lianas delgadas y largas tan flexibles como látigos." },
  "stomp": { name: "Pisotón", description: "Tremendo pisotón que puede hacer que el objetivo se amedrente." },
  "double-kick": { name: "Doble patada", description: "Propina dos patadas seguidas, una con cada pie." },
  "mega-kick": { name: "Megapatada", description: "Patada de extrema fuerza." },
  "jump-kick": { name: "Patada salto", description: "Da un salto y pega una patada. Si falla, se lesiona." },
  "rolling-kick": { name: "Patada giro", description: "Da una patada rápida y circular. Puede hacer retroceder al objetivo." },
  "sand-attack": { name: "Ataque arena", description: "Arroja arena a la cara del objetivo y reduce su Precisión." },
  "headbutt": { name: "Golpe cabeza", description: "Potente cabezazo que puede amedrentar al objetivo." },
  "horn-attack": { name: "Ataque cuerno", description: "Ataca al objetivo con una cornada punzante." },
  "fury-attack": { name: "Ataque furia", description: "Cornea o picotea al objetivo de dos a cinco veces seguidas." },
  "horn-drill": { name: "Cuerno taladro", description: "Ataque con un cuerno giratorio que fulmina al objetivo de un solo golpe si acierta." },
  "tackle": { name: "Tacleada", description: "Embestida con todo el cuerpo." },
  "body-slam": { name: "Golpe de cuerpo", description: "Salta sobre el objetivo con todo su peso y puede llegar a paralizarlo." },
  "wrap": { name: "Constricción", description: "Oprime al objetivo de cuatro a cinco turnos con lianas o con su cuerpo." },
  "take-down": { name: "Derribo", description: "Carga desmedida que también hiere ligeramente al usuario." },
  "thrash": { name: "Golpiza", description: "El usuario ataca enfurecido durante dos o tres turnos y, después, se queda confuso." },
  "double-edge": { name: "Doble filo", description: "Ataque arriesgado que también hiere seriamente al usuario." },
  "tail-whip": { name: "Látigo de cola", description: "Agita la cola para despistar al objetivo y reducir su Defensa." },
  "poison-sting": { name: "Piquete venenoso", description: "Lanza un aguijón tóxico que puede envenenar al objetivo." },
  "twineedle": { name: "Doble aguijón", description: "Pincha dos veces con dos espinas. Puede envenenar." },
  "pin-missile": { name: "Misil aguja", description: "Lanza afiladas púas que hieren al objetivo de dos a cinco veces seguidas." },
  "leer": { name: "Malicioso", description: "Intimida al objetivo con una mirada torva para reducir su Defensa." },
  "bite": { name: "Mordida", description: "Un voraz bocado con dientes afilados que puede amedrentar al objetivo." },
  "growl": { name: "Gruñido", description: "Dulce gruñido que distrae al objetivo para que baje la guardia y reduce su Ataque." },
  "roar": { name: "Rugido", description: "Se lleva al objetivo, que es cambiado por otro Pokémon. Si es un Pokémon salvaje, acaba el combate." },
  "sing": { name: "Canto", description: "Cancioncilla que hace dormir profundamente al objetivo." },
  "supersonic": { name: "Supersónico", description: "El cuerpo del usuario emite unas ondas sónicas raras que confunden al objetivo." },
  "sonic-boom": { name: "Explosión sónica", description: "Lanza ondas de choque que restan 20 PS al objetivo." },
  "disable": { name: "Anulación", description: "Anula el último movimiento usado por el objetivo durante cuatro turnos." },
  "acid": { name: "Ácido", description: "Rocía al objetivo con un ácido corrosivo. Puede reducir la Defensa Especial." },
  "ember": { name: "Brasas", description: "Ataca con llamas pequeñas que pueden causar quemaduras." },
  "flamethrower": { name: "Lanzallamas", description: "Chorro de fuego que quema al objetivo y puede causarle quemaduras." },
  "mist": { name: "Niebla", description: "Neblina que rodea al usuario para evitar la reducción de sus características." },
  "water-gun": { name: "Pistola agua", description: "Lanza un chorro de agua contra el objetivo." },
  "hydro-pump": { name: "Hidrobomba", description: "Potente chorro de agua que golpea con enorme fuerza al objetivo." },
  "surf": { name: "Surf", description: "Inunda el terreno de combate con una ola gigante que golpea a los Pokémon adyacentes." },
  "ice-beam": { name: "Rayo de hielo", description: "Rayo de hielo que puede llegar a congelar." },
  "blizzard": { name: "Ventisca", description: "Tormenta de hielo que puede llegar a congelar." },
  "psybeam": { name: "Psicorrayo", description: "Extraño rayo que puede causar confusión." },
  "bubble-beam": { name: "Rayo burbuja", description: "Ráfaga de burbujas que puede reducir la Velocidad." },
  "aurora-beam": { name: "Rayo aurora", description: "Rayo multicolor que puede reducir el Ataque." },
  "hyper-beam": { name: "Hiperrayo", description: "El usuario ataca al objetivo con un potente haz de luz, pero deberá descansar en el siguiente turno." },
  "peck": { name: "Picotazo", description: "Ensarta al objetivo con un cuerno o pico punzante." },
  "drill-peck": { name: "Picotazo taladro", description: "Ensarta al objetivo con un pico giratorio como un taladro." },
  "submission": { name: "Sumisión", description: "Ataque de lucha que lesiona al usuario ligeramente." },
  "low-kick": { name: "Patada baja", description: "Patada baja rápida que puede derribar al objetivo." },
  "counter": { name: "Contraataque", description: "Contraataca devolviendo el daño físico recibido con el doble de potencia." },
  "seismic-toss": { name: "Sísmico", description: "Aprovecha la gravedad para derribar al objetivo. Le resta tantos PS como nivel tenga el usuario." },
  "strength": { name: "Fuerza", description: "Ataca al objetivo golpeándolo con todas sus fuerzas." },
  "absorb": { name: "Absorción", description: "Un ataque que absorbe nutrientes. El usuario recupera la mitad de los PS del daño que produce." },
  "mega-drain": { name: "Megadrenado", description: "Un ataque que absorbe nutrientes. El usuario recupera la mitad de los PS del daño que produce." },
  "leech-seed": { name: "Drenadoras", description: "Planta semillas que absorben PS del objetivo en cada turno y que le sirven para recuperarse." },
  "growth": { name: "Crecimiento", description: "Hace que su cuerpo crezca a marchas forzadas, con lo que aumenta su Ataque y su Ataque Especial." },
  "razor-leaf": { name: "Hojas navaja", description: "Corta con hojas afiladas. Suele asestar un golpe crítico." },
  "solar-beam": { name: "Rayo solar", description: "El usuario absorbe luz en el primer turno y, en el segundo, lanza un potente rayo de energía." },
  "poison-powder": { name: "Polvo venenoso", description: "Esparce polvo tóxico que envenena al objetivo." },
  "stun-spore": { name: "Paralizador", description: "Esparce polvo que paraliza al objetivo." },
  "sleep-powder": { name: "Somnífero", description: "Esparce polvo que duerme al objetivo." },
  "petal-dance": { name: "Danza de pétalos", description: "Ataca al objetivo lanzando pétalos de dos a tres turnos y, al finalizar, el usuario se queda confuso." },
  "string-shot": { name: "Disparo de seda", description: "Lanza seda por la boca al objetivo y reduce mucho su Velocidad." },
  "dragon-rage": { name: "Furia dragón", description: "Ráfaga de furiosas ondas de choque que quitan 40 PS." },
  "fire-spin": { name: "Giro fuego", description: "Un aro de fuego que atrapa y daña al objetivo de cuatro a cinco turnos." },
  "thunder-shock": { name: "Impactrueno", description: "Ataque eléctrico que puede paralizar al objetivo." },
  "thunderbolt": { name: "Atactrueno", description: "Potente ataque eléctrico que puede paralizar al objetivo." },
  "thunder-wave": { name: "Onda trueno", description: "Una ligera descarga que paraliza al objetivo." },
  "thunder": { name: "Trueno", description: "Un poderoso rayo que daña al objetivo y puede paralizarlo." },
  "rock-throw": { name: "Lanzarrocas", description: "Tira una pequeña roca al objetivo." },
  "earthquake": { name: "Terremoto", description: "Un terremoto que afecta a los Pokémon adyacentes." },
  "fissure": { name: "Fisura", description: "Abre una grieta en el suelo y mete al objetivo en ella. Fulmina al objetivo de un solo golpe si acierta." },
  "dig": { name: "Excavación", description: "El usuario se hunde en el suelo en el primer turno y golpea en el segundo." },
  "toxic": { name: "Tóxico", description: "Envenena gravemente al objetivo de forma que pierde PS cada turno." },
  "confusion": { name: "Confusión", description: "Ataque que confunde al objetivo." },
  "psychic": { name: "Psíquico", description: "Potente ataque que puede reducir la Defensa Especial del objetivo." },
  "hypnosis": { name: "Hipnosis", description: "Hipnotiza al objetivo para hacerlo dormir." },
  "meditate": { name: "Meditación", description: "El usuario medita en el acto para aumentar su Ataque." },
  "agility": { name: "Agilidad", description: "Se concentra en acelerar su cuerpo para aumentar mucho su Velocidad." },
  "quick-attack": { name: "Ataque rápido", description: "Ataque rápido que permite atacar primero." },
  "rage": { name: "Furia", description: "Al usarse, aumenta el Ataque del usuario cada vez que es golpeado." },
  "teleport": { name: "Teletransporte", description: "Permite al usuario cambiarse por otro Pokémon del equipo, si lo hay. Si un Pokémon salvaje usa este movimiento, huye del combate." },
  "night-shade": { name: "Tinieblas", description: "Produce un espejismo ante el objetivo, que pierde tantos PS como nivel tenga el usuario." },
  "mimic": { name: "Mímica", description: "Copia el último movimiento usado por el objetivo, y puede utilizarlo mientras esté en el combate." },
  "screech": { name: "Chillido", description: "Alarido agudo que reduce mucho la Defensa del objetivo." },
  "double-team": { name: "Doble equipo", description: "El usuario se mueve a velocidad vertiginosa y crea copias ilusorias de sí mismo, con lo que aumenta su Evasión al desconcertar al rival." },
  "recover": { name: "Recuperación", description: "El usuario regenera sus células y recupera una cantidad de PS equivalente a la mitad de sus PS máximos." },
  "harden": { name: "Fortaleza", description: "El usuario tensa su musculatura para aumentar la Defensa." },
  "minimize": { name: "Reducción", description: "El usuario mengua para aumentar mucho la Evasión." },
  "smokescreen": { name: "Pantalla de humo", description: "Reduce la Precisión del objetivo con una nube de humo o tinta." },
  "confuse-ray": { name: "Rayo de confusión", description: "Rayo siniestro que confunde al objetivo." },
  "withdraw": { name: "Refugio", description: "El usuario se resguarda en su coraza, por lo que le aumenta la Defensa." },
  "defense-curl": { name: "Hacerse bolita", description: "Se enrosca para ocultar sus puntos débiles y aumentar la Defensa." },
  "barrier": { name: "Barrera", description: "Crea una barrera que aumenta mucho la Defensa." },
  "light-screen": { name: "Pantalla de luz", description: "Barrera misteriosa que reduce durante cinco turnos el daño producido por los ataques especiales del rival." },
  "haze": { name: "Niebla", description: "Neblina oscura que elimina los cambios en las características de todos los Pokémon en combate." },
  "reflect": { name: "Reflejo", description: "Barrera misteriosa que reduce durante cinco turnos el daño producido por los ataques físicos del rival." },
  "focus-energy": { name: "Centrar energía", description: "Concentra energía para aumentar las posibilidades de asestar un golpe crítico." },
  "bide": { name: "Venganza", description: "Espera dos turnos para atacar con el doble de potencia del daño recibido." },
  "metronome": { name: "Metrónomo", description: "Mueve un dedo y estimula su cerebro para usar al azar casi cualquier movimiento." },
  "mirror-move": { name: "Espejo", description: "Ataca al objetivo con el último movimiento que este haya usado." },
  "self-destruct": { name: "Autodestrucción", description: "El atacante explota y hiere a los Pokémon adyacentes. El usuario se debilita de inmediato." },
  "egg-bomb": { name: "Bomba huevo", description: "Arroja un huevo enorme al objetivo con gran fuerza." },
  "lick": { name: "Lengüetazo", description: "El usuario ataca al objetivo lamiéndolo con su larga lengua. Puede causar parálisis." },
  "smog": { name: "Tóxico", description: "Nube de gas que envenena al objetivo." },
  "sludge-bomb": { name: "Bomba cieno", description: "Lanza cieno pegajoso que puede envenenar al objetivo." },
  "bone-club": { name: "Garrote óseo", description: "Golpea con un hueso pesado que puede amedrentar al objetivo." },
  "fire-blast": { name: "Explosión ígnea", description: "Explosión de fuego controlada que puede causar quemaduras." },
  "waterfall": { name: "Cascada", description: "Embiste con un gran impulso y puede llegar a amedrentar al objetivo." },
  "clamp": { name: "Tenaza", description: "Atrapa y atenaza con fuerza durante cuatro o cinco turnos." },
  "swift": { name: "Meteoros", description: "Lanza rayos en forma de estrella que no fallan nunca." },
  "skull-bash": { name: "Cabezazo", description: "El usuario se prepara y sube su Defensa en el primer turno y en el segundo arremete con un cabezazo." },
  "spike-cannon": { name: "Cañón de púas", description: "Lanza finas púas que hieren de dos a cinco veces." },
  "constrict": { name: "Restricción", description: "Ataca con largos tentáculos o zarcillos que pueden bajar la Velocidad." },
  "amnesia": { name: "Amnesia", description: "El usuario olvida sus preocupaciones y aumenta mucho la Defensa Especial." },
  "kinesis": { name: "Kinético", description: "Dobla una cuchara para distraer al objetivo y reducir su Precisión." },
  "soft-boiled": { name: "Ovocuración", description: "Restaura la mitad de los PS máximos del usuario." },
  "high-jump-kick": { name: "Patada salto alto", description: "El usuario salta muy alto y propina un rodillazo al objetivo. Si falla, se hiere a sí mismo." },
  "glare": { name: "Fulmirada", description: "Intimida y asusta al objetivo con la mirada para dejarlo paralizado." },
  "dream-eater": { name: "Comesueños", description: "Engulle los sueños de un objetivo dormido. El usuario recupera la mitad de los PS del daño que produce." },
  "poison-gas": { name: "Gas venenoso", description: "Lanza una nube de gas tóxico al rostro del objetivo. Produce envenenamiento." },
  "barrage": { name: "Bombardeo", description: "Arroja esferas al objetivo entre dos y cinco veces seguidas." },
  "leech-life": { name: "Chupavidas", description: "Chupa sangre al objetivo. El usuario recupera la mitad de los PS del daño que produce." },
  "lovely-kiss": { name: "Beso amoroso", description: "Intimida al objetivo con una cara que asusta y le da un beso que lo deja dormido." },
  "sky-attack": { name: "Ataque celestial", description: "Ataca en el segundo turno y suele asestar un golpe crítico. También puede amedrentar al objetivo." },
  "transform": { name: "Transformación", description: "El usuario se transforma en una copia del objetivo, con los mismos movimientos." },
  "bubble": { name: "Burbuja", description: "Lanza burbujas a los contrincantes y puede reducir su Velocidad." },
  "dizzy-punch": { name: "Puño mareador", description: "Rítmicos puñetazos que pueden causar confusión." },
  "spore": { name: "Esporas", description: "Esparce esporas que inducen el sueño." },
  "flash": { name: "Destello", description: "Luz cegadora que baja la Precisión del objetivo." },
  "psywave": { name: "Psicoonda", description: "Ataque con una onda de energía de intensidad variable." },
  "splash": { name: "Salpicadura", description: "No tiene ningún efecto. Solo salpica." },
  "acid-armor": { name: "Armadura ácida", description: "Transforma su estructura celular para hacerse líquido y aumentar mucho la Defensa." },
  "crabhammer": { name: "Garra de cangrejo", description: "Poderoso golpe con las pinzas que suele asestar un golpe crítico." },
  "explosion": { name: "Explosión", description: "El usuario explota y hiere a los Pokémon adyacentes, debilitándose de inmediato." },
  "fury-swipes": { name: "Arañazo furia", description: "Ataque rápido con las garras que golpea de dos a cinco veces." },
  "bonemerang": { name: "Huesomerang", description: "Lanza el hueso que lleva a modo de bumerán contra el objetivo y le inflige daño dos veces seguidas." },
  "rest": { name: "Descanso", description: "Restaura todos los PS y cura todos los problemas de estado del usuario, que se duerme los dos turnos siguientes." },
  "rock-slide": { name: "Avalancha", description: "Lanza grandes pedruscos. Puede amedrentar al objetivo." },
  "hyper-fang": { name: "Hipercolmillo", description: "Ataca con agudos colmillos. Puede amedrentar al objetivo." },
  "sharpen": { name: "Afilar", description: "El perfil del usuario se hace más afilado y su Ataque mejora." },
  "conversion": { name: "Conversión", description: "Cambia el tipo del usuario por el del primer movimiento en su lista." },
  "tri-attack": { name: "Triataque", description: "Ataque con tres rayos de luz que puede paralizar, quemar o congelar al objetivo." },
  "super-fang": { name: "Megacolmillo", description: "Reduce a la mitad los PS del objetivo." },
  "struggle": { name: "Forcejeo", description: "Solo se usa como último recurso al acabarse los PP. El usuario se hiere ligeramente a sí mismo." },
  "sketch": { name: "Boceto", description: "Aprende de forma permanente el último movimiento utilizado por el objetivo. Es de un solo uso." },
  "triple-kick": { name: "Triple patada", description: "Propina hasta tres patadas seguidas, la potencia de las cuales aumenta cada vez que acierta." },
  "thief": { name: "Ladrón", description: "El usuario ataca y le roba el objeto al objetivo. Si ya lleva uno, el robo no se produce." },
  "spider-web": { name: "Telaraña", description: "Enreda al objetivo para evitar que abandone el combate." },
  "mind-reader": { name: "Telépata", description: "El usuario adivina los movimientos del objetivo para hacer que su siguiente ataque no falle." },
  "nightmare": { name: "Pesadilla", description: "El objetivo dormido sufre una pesadilla que le hace perder PS en cada turno." },
  "flame-wheel": { name: "Rueda ígnea", description: "Ataca envuelto en fuego. Puede causar quemaduras." },
  "snore": { name: "Ronquido", description: "Fuerte ronquido que solo puede usarse dormido. Puede amedrentar al objetivo." },
  "curse": { name: "Maldición", description: "Un movimiento que tiene efectos distintos si el usuario es de tipo Fantasma o no." },
  "flail": { name: "Azote", description: "Ataque frenético. Cuantos menos PS tenga el usuario, más daño producirá." },
  "conversion-2": { name: "Conversión 2", description: "El usuario cambia de tipo para hacerse resistente al tipo del último movimiento usado por el objetivo." },
  "aeroblast": { name: "Aerochorro", description: "Lanza un chorro de aire que suele asestar un golpe crítico." },
  "cotton-spore": { name: "Esporagodón", description: "Adhiere esporas al objetivo para reducir mucho su Velocidad." },
  "reversal": { name: "Inversión", description: "Ataque desesperado que causa más daño cuantos menos PS tenga el usuario." },
  "spite": { name: "Rencor", description: "Reduce los PP del último movimiento usado por el objetivo." },
  "powder-snow": { name: "Polvo nieve", description: "Viento gélido que puede congelar al objetivo." },
  "protect": { name: "Protección", description: "Frena todos los ataques, pero puede fallar si se usa repetidamente." },
  "mach-punch": { name: "Puño velocidad", description: "Puñetazo ultrasónico de velocidad extrema. Este movimiento tiene prioridad alta." },
  "scary-face": { name: "Cara aterradora", description: "Asusta al objetivo para reducir mucho su Velocidad." },
  "feint-attack": { name: "Ataque finta", description: "Engaña al objetivo para acercarse y dar un puñetazo que no falla." },
  "sweet-kiss": { name: "Beso dulce", description: "Da un beso con tal dulzura que causa confusión." },
  "belly-drum": { name: "Tambor", description: "Sacrifica la mitad de los PS máximos para aumentar al máximo el Ataque." },
  "sludge-wave": { name: "Onda lodo", description: "Onda de lodo que daña a los Pokémon adyacentes y puede envenenar." },
  "mud-slap": { name: "Bofetón lodo", description: "Golpea al objetivo con lodo y reduce su Precisión." },
  "octazooka": { name: "Octobomba", description: "Lanza un chorro de tinta que reduce la Precisión del objetivo." },
  "spikes": { name: "Púas", description: "Lanza una trampa de púas a los pies del objetivo que hiere a los rivales que entran en combate." },
  "zap-cannon": { name: "Electrocañón", description: "Dispara una descarga eléctrica que causa daño y parálisis." },
  "foresight": { name: "Visión", description: "Permite atacar con cualquier movimiento a objetivos de tipo Fantasma y golpear a Pokémon evasivos." },
  "destiny-bond": { name: "Destino", description: "Si el usuario se debilita al recibir un ataque, su atacante se debilita de inmediato." },
  "perish-song": { name: "Canto mortal", description: "Canción que cuenta tres turnos hacia atrás para debilitar a todos los Pokémon en combate." },
  "icy-wind": { name: "Viento helado", description: "Viento gélido que golpea al objetivo y reduce su Velocidad." },
  "detect": { name: "Detección", description: "Frena todos los ataques, pero puede fallar si se usa repetidamente." },
  "bone-rush": { name: "Hueso veloz", description: "Hueso en ristre, aporrea al objetivo de dos a cinco veces seguidas." },
  "lock-on": { name: "Fijar blanco", description: "Fija el blanco para que el siguiente movimiento no falle." },
  "outrage": { name: "Enfado", description: "El usuario ataca enfurecido durante dos o tres turnos y, después, se queda confuso." },
  "sandstorm": { name: "Tormenta de arena", description: "Tormenta de arena que dura cinco turnos y hiere a todos, excepto a los de tipo Roca, Tierra y Acero, y aumenta la Defensa Especial de los de tipo Roca." },
  "giga-drain": { name: "Gigadrenado", description: "Un ataque que absorbe nutrientes. El usuario recupera la mitad de los PS del daño que produce." },
  "endure": { name: "Aguante", description: "Resiste cualquier ataque y deja al menos 1 PS. Puede fallar si se usa repetidamente." },
  "charm": { name: "Encanto", description: "Engatusa al objetivo y reduce mucho su Ataque." },
  "rollout": { name: "Rodada", description: "El usuario rueda contra el objetivo durante cinco turnos y, cada vez que acierta, aumenta la potencia del movimiento." },
  "false-swipe": { name: "Falsa bofetada", description: "Ataque moderado que no debilita al objetivo y le deja al menos 1 PS." },
  "swagger": { name: "Fanfarronear", description: "Hace enfurecer y confunde al objetivo, pero también aumenta mucho su Ataque." },
  "milk-drink": { name: "Licuado", description: "Restaura la mitad de los PS máximos del usuario." },
  "spark": { name: "Chispa", description: "Se envuelve de electricidad y arremete contra el objetivo. Puede llegar a paralizar." },
  "fury-cutter": { name: "Corte furia", description: "Ataque lacerante con garras, cuchillas o similares cuya potencia aumenta si se usa varias veces seguidas." },
  "steel-wing": { name: "Ala de acero", description: "Golpea al objetivo con unas alas robustas y macizas. Puede aumentar la Defensa del usuario." },
  "mean-look": { name: "Mal de ojo", description: "Mal de ojo que impide al objetivo huir del combate o ser cambiado por otro." },
  "attract": { name: "Atracción", description: "Si el objetivo es del sexo opuesto, se enamorará y bajará la posibilidad de que ataque." },
  "sleep-talk": { name: "Sonámbulo", description: "Mientras duerme, usa uno de sus movimientos elegido al azar." },
  "heal-bell": { name: "Cascabel sanador", description: "Tañido que cura los problemas de estado del bando del usuario." },
  "return": { name: "Retribución", description: "Cuanto mayor sea la amistad con el Entrenador, más poderoso será este ataque." },
  "present": { name: "Obsequio", description: "El usuario ataca al objetivo dándole un regalo con una bomba trampa. Sin embargo, a veces restaura sus PS." },
  "frustration": { name: "Frustración", description: "Cuanto menor sea la amistad con el Entrenador, más poderoso será este ataque." },
  "safeguard": { name: "Velo sagrado", description: "Un poder misterioso que protege de problemas de estado durante cinco turnos." },
  "pain-split": { name: "Dividedolor", description: "Suma los PS del usuario a los del objetivo y los reparte a partes iguales." },
  "sacred-fire": { name: "Fuego sagrado", description: "Fuego místico de gran intensidad que puede causar quemaduras." },
  "magnitude": { name: "Magnitud", description: "Sacudida sísmica de intensidad variable que afecta a todos los Pokémon a su alrededor." },
  "dynamic-punch": { name: "Puño dinámico", description: "Puñetazo con toda la fuerza concentrada que causa confusión." },
  "megahorn": { name: "Megacuerno", description: "Ensarta al objetivo con su imponente cuerno o cornamenta." },
  "dragon-breath": { name: "Aliento dragón", description: "Poderosa ráfaga de aliento que golpea al objetivo y puede paralizarlo." },
  "baton-pass": { name: "Relevo", description: "Cambia el puesto con otro miembro del equipo y le pasa los cambios en las características." },
  "encore": { name: "Otra vez", description: "El objetivo repite su último movimiento durante tres turnos." },
  "pursuit": { name: "Persecución", description: "Hace el doble de daño al objetivo que pide el relevo." },
  "rapid-spin": { name: "Giro rápido", description: "Ataque giratorio que anula los efectos de movimientos como Atadura, Constricción y Drenadoras. También aumenta la Velocidad del usuario." },
  "sweet-scent": { name: "Dulce aroma", description: "Un dulce aroma engatusa al objetivo, por lo que se reduce mucho su Evasión." },
  "iron-tail": { name: "Cola de hierro", description: "Ataca con una cola férrea y puede reducir la Defensa del objetivo." },
  "metal-claw": { name: "Garra de metal", description: "Ataque con garras de acero que puede aumentar el Ataque del usuario." },
  "vital-throw": { name: "Llave vital", description: "El usuario ataca el último, pero no falla." },
  "morning-sun": { name: "Sol matutino", description: "Restaura PS del usuario. La cantidad varía según el tiempo que haga." },
  "synthesis": { name: "Fotosíntesis", description: "Restaura PS del usuario. La cantidad varía según el tiempo que haga." },
  "moonlight": { name: "Luz lunar", description: "Restaura PS del usuario. La cantidad varía según el tiempo que haga." },
  "hidden-power": { name: "Poder oculto", description: "Movimiento cuyo tipo varía en función del Pokémon que lo usa." },
  "cross-chop": { name: "Golpe cruzado", description: "Golpe doble con las manos que suele asestar un golpe crítico." },
  "twister": { name: "Tornado", description: "Crea un violento tornado para hacer trizas al objetivo. Puede amedrentarlo." },
  "rain-dance": { name: "Danza de lluvia", description: "Genera una fuerte lluvia que dura cinco turnos, lo que potencia los movimientos de tipo Agua y debilita los de tipo Fuego." },
  "sunny-day": { name: "Día soleado", description: "Hace que se intensifique el efecto del sol durante cinco turnos, lo que potencia los movimientos de tipo Fuego y debilita los de tipo Agua." },
  "crunch": { name: "Triturar", description: "Tritura con afilados colmillos y puede reducir la Defensa del objetivo." },
  "mirror-coat": { name: "Escudo espejo", description: "Responde a un ataque especial ocasionando el doble del daño recibido." },
  "psych-up": { name: "Autosugestión", description: "El usuario se sume en un trance y copia cualquier cambio que haya en las características de su objetivo." },
  "extreme-speed": { name: "Velocidad extrema", description: "Ataque de una velocidad extrema. Este movimiento tiene prioridad alta." },
  "ancient-power": { name: "Poder antiguo", description: "Canaliza un poder prehistórico con el que ataca al objetivo. Puede aumentar todas las características del usuario." },
  "shadow-ball": { name: "Bola sombra", description: "Lanza una bola oscura que puede reducir la Defensa Especial del objetivo." },
  "future-sight": { name: "Premonición", description: "Concentra energía psíquica para golpear al objetivo dos turnos después." },
  "rock-smash": { name: "Golpe roca", description: "Propina un gran puñetazo que puede reducir la Defensa del objetivo." },
  "whirlpool": { name: "Remolino", description: "Una tromba de agua atrapa y daña al objetivo durante cuatro o cinco turnos." },
  "beat-up": { name: "Paliza", description: "Ataque de todo el equipo Pokémon. Cuantos más haya, más veces se atacará." },
  "fake-out": { name: "Sorpresa", description: "Amedrenta al objetivo con este movimiento de prioridad alta. Solo tiene efecto si el usuario lo usa nada más entrar en combate." },
  "uproar": { name: "Alboroto", description: "Ataca de forma alborotada durante tres turnos. Mantiene despiertos a todos." },
  "stockpile": { name: "Reserva", description: "Acumula energía hasta un máximo de tres veces para aumentar la Defensa y la Defensa Especial." },
  "spit-up": { name: "Escupida", description: "Libera de una vez la energía acumulada con Reserva. La potencia del movimiento será proporcional a la cantidad de energía acumulada." },
  "swallow": { name: "Tragar", description: "Absorbe la energía acumulada con Reserva para recobrar salud. Cuanta más se haya acumulado, mayor será el número de PS que se recuperen." },
  "heat-wave": { name: "Onda ígnea", description: "Provoca un viento abrasador que daña al objetivo y puede causar quemaduras." },
  "hail": { name: "Granizo", description: "Tormenta de granizo que dura cinco turnos. Hiere a todos los Pokémon excepto a los de tipo Hielo." },
  "torment": { name: "Tormento", description: "Atormenta y enfurece al objetivo, que no puede usar dos veces seguidas el mismo movimiento." },
  "flatter": { name: "Halago", description: "Halaga al objetivo y lo confunde, pero también aumenta su Ataque Especial." },
  "will-o-wisp": { name: "Bola fuego", description: "Lanza una bola de fuego que quema al objetivo." },
  "memento": { name: "Testamento", description: "El usuario se debilita de inmediato, pero reduce el Ataque y el Ataque Especial del objetivo de forma sustancial." },
  "focus-punch": { name: "Puño centrado", description: "Se concentra para dar un puñetazo. Falla si se sufre un golpe antes de su uso." },
  "smelling-salts": { name: "Estímulo", description: "Hace el doble de daño a objetivos paralizados, pero también cura la parálisis." },
  "follow-me": { name: "Señuelo", description: "Llama la atención para centrar sobre sí todos los movimientos de los rivales." },
  "nature-power": { name: "Adaptación", description: "Usa el poder de la naturaleza para atacar. Su efecto varía según el entorno de combate." },
  "charge": { name: "Carga", description: "Recarga energía para potenciar su siguiente movimiento de tipo Eléctrico. También aumenta la Defensa Especial." },
  "taunt": { name: "Provocación", description: "Enfurece al objetivo para que solo use movimientos de ataque durante tres turnos." },
  "helping-hand": { name: "Refuerzos", description: "El usuario ayuda a un aliado reforzando la potencia de su ataque." },
  "trick": { name: "Truco", description: "Engaña al objetivo desprevenido e intercambia su objeto con él." },
  "role-play": { name: "Imitación", description: "Imita al objetivo por completo y copia su habilidad." },
  "wish": { name: "Deseo", description: "Restaura en el siguiente turno la mitad de los PS máximos del usuario o se los pasa al Pokémon que lo sustituye." },
  "assist": { name: "Ayuda", description: "Usa un movimiento de un miembro del equipo elegido al azar." },
  "ingrain": { name: "Arraigo", description: "Echa raíces para recuperar PS en cada turno, pero impide que pueda huir o ser cambiado por otro." },
  "superpower": { name: "Fuerza bruta", description: "Ataque de gran potencia, pero que reduce el Ataque y la Defensa del usuario." },
  "magic-coat": { name: "Capa mágica", description: "Barrera capaz de devolver al agresor movimientos como Drenadoras y otros que alteran el estado o las características." },
  "recycle": { name: "Reciclaje", description: "Recicla y así recupera un objeto equipado de un solo uso que ya haya sido empleado durante el combate." },
  "revenge": { name: "Desquite", description: "Ataque que produce el doble de daño si el usuario resulta herido en el mismo turno." },
  "brick-break": { name: "Karatazo", description: "Ataca al objetivo con un potente golpe con el filo de la mano capaz de destruir barreras como Pantalla de Luz y Reflejo." },
  "yawn": { name: "Bostezo", description: "Gran bostezo que induce el sueño en el objetivo en el siguiente turno." },
  "knock-off": { name: "Desarme", description: "Hace que el objetivo suelte el objeto que lleva y le impide usarlo hasta que concluye el combate. Inflige más daño si el objetivo lleva un objeto." },
  "endeavor": { name: "Esfuerzo", description: "Reduce los PS del objetivo para que igualen a los del usuario." },
  "eruption": { name: "Estallido", description: "Furia explosiva. Cuanto menor sea el número de PS del usuario, menos potencia tendrá el movimiento." },
  "skill-swap": { name: "Intercambio", description: "Usa el poder psíquico para intercambiar habilidades con el objetivo." },
  "imprison": { name: "Sellar", description: "Impide a los rivales usar movimientos conocidos por el usuario durante el combate." },
  "refresh": { name: "Alivio", description: "Descansa para curar parálisis, envenenamiento o quemaduras." },
  "grudge": { name: "Rabia", description: "Si el usuario se debilita al recibir un ataque, todos los PP de este último ataque serán eliminados." },
  "snatch": { name: "Robo", description: "Roba el efecto de los movimientos de curación o de cambio de características que se usen." },
  "secret-power": { name: "Poder secreto", description: "Ataque cuyos efectos secundarios varían según el entorno de combate." },
  "dive": { name: "Buceo", description: "El usuario se sumerge en el primer turno y ataca en el segundo." },
  "arm-thrust": { name: "Golpe múltiple", description: "Propina golpes rápidos múltiples al objetivo con sus alas, brazos, etc. de dos a cinco veces seguidas." },
  "camouflage": { name: "Camuflaje", description: "Cambia el tipo del usuario para integrarse con el terreno." },
  "teeter-dance": { name: "Danza del caos", description: "Danza histérica que confunde a los Pokémon adyacentes." },
  "blaze-kick": { name: "Patada ígnea", description: "Patada que suele asestar un golpe crítico y puede causar quemaduras." },
  "mud-sport": { name: "Chapoteo de lodo", description: "El usuario esparce lodo a su alrededor, lo que debilita los movimientos de tipo Eléctrico durante cinco turnos." },
  "ice-ball": { name: "Bola nieve", description: "Bola de nieve que golpea durante cinco turnos. La potencia aumenta con cada golpe." },
  "needle-arm": { name: "Púa", description: "Ataca con afiladas púas que pueden hacer que el objetivo se amedrente." },
  "slack-off": { name: "Pereza", description: "Se relaja y devuelve la mitad de los PS máximos al usuario." },
  "hyper-voice": { name: "Hipervoz", description: "Grito potente que causa daño a todos los Pokémon adyacentes." },
  "poison-fang": { name: "Colmillo veneno", description: "Mordedura con colmillos venenosos que inflige daño al objetivo y puede envenenarlo gravemente." },
  "crush-claw": { name: "Garra brutal", description: "Hace trizas al objetivo con garras afiladas y puede reducir su Defensa." },
  "blast-burn": { name: "Anillo de fuego", description: "Calcina al objetivo con una explosión de fuego. El usuario deberá descansar en el siguiente turno." },
  "hydro-cannon": { name: "Hidrocañón", description: "Ataca al objetivo con un cañonazo de agua. El usuario deberá descansar en el siguiente turno." },
  "meteor-mash": { name: "Puño meteoro", description: "Puñetazo que impacta como un meteorito y puede aumentar el Ataque del usuario." },
  "astonish": { name: "Impresión", description: "Asusta al objetivo con, por ejemplo, un grito y le propina un ataque que puede amedrentarlo." },
  "weather-ball": { name: "Meteorobola", description: "El tipo y la potencia del movimiento varían según el tiempo que haga." },
  "aromatherapy": { name: "Aromaterapia", description: "Cura todos los problemas de estado del equipo con un suave aroma." },
  "fake-tears": { name: "Llanto falso", description: "Lágrimas de cocodrilo que reducen mucho la Defensa Especial del objetivo." },
  "air-cutter": { name: "Aire cortante", description: "Viento cortante que azota. Suele asestar un golpe crítico." },
  "overheat": { name: "Supercalor", description: "Ataca al objetivo con toda su fuerza, pero reduce mucho el Ataque Especial del usuario." },
  "odor-sleuth": { name: "Rastreo", description: "Permite atacar con cualquier movimiento a objetivos de tipo Fantasma y golpear a Pokémon evasivos." },
  "rock-tomb": { name: "Tumba de rocas", description: "Lanza rocas que infligen daño al objetivo y reducen su Velocidad al dificultar sus movimientos." },
  "silver-wind": { name: "Viento plateado", description: "Fuerte viento con polvo de escamas. Puede subir todas las características de quien lo usa." },
  "metal-sound": { name: "Sonido metálico", description: "Horrible chirrido metálico que reduce mucho la Defensa Especial del objetivo." },
  "grass-whistle": { name: "Silbato de hoja", description: "Agradable melodía que adormece al objetivo." },
  "tickle": { name: "Cosquillas", description: "Hace reír al objetivo para reducir su Ataque y su Defensa." },
  "cosmic-power": { name: "Masa cósmica", description: "Absorbe una energía mística proveniente del espacio que aumenta su Defensa y su Defensa Especial." },
  "water-spout": { name: "Columna de agua", description: "Chorro de agua. Cuantos menos PS tenga el usuario, menos potencia tendrá el movimiento." },
  "signal-beam": { name: "Rayo señal", description: "Ataca con un rayo de luz siniestro. Puede confundir al objetivo." },
  "shadow-punch": { name: "Puño sombra", description: "Puñetazo procedente de las sombras que no falla nunca." },
  "extrasensory": { name: "Extrasensorial", description: "Emite una energía muy extraña que puede amedrentar al objetivo." },
  "sky-uppercut": { name: "Corte elevado", description: "Gancho ascendente de gran ímpetu." },
  "sand-tomb": { name: "Tumba de arena", description: "Envuelve al objetivo en un violento remolino de arena que le inflige daño de cuatro a cinco turnos." },
  "sheer-cold": { name: "Frío extremo", description: "Fulmina al objetivo de un solo golpe. Si lo usa un Pokémon que no sea de tipo Hielo, es difícil que acierte." },
  "muddy-water": { name: "Agua lodosa", description: "Ataque con agua lodosa que puede reducir la Precisión del objetivo." },
  "bullet-seed": { name: "Bala semilla", description: "Dispara rápido ráfagas de semillas de dos a cinco veces seguidas." },
  "aerial-ace": { name: "As aéreo", description: "Desconcierta al objetivo con movimientos muy rápidos antes de cercenarlo. No falla nunca." },
  "icicle-spear": { name: "Lanza de hielo", description: "Lanza carámbanos afilados al objetivo de dos a cinco veces seguidas." },
  "iron-defense": { name: "Defensa hierro", description: "Fortalece el cuerpo como si fuera de hierro y aumenta mucho la Defensa." },
  "block": { name: "Bloqueo", description: "Le corta el paso al objetivo para que no pueda huir ni ser cambiado por otro." },
  "howl": { name: "Aullido", description: "Aullido que sube el ánimo y aumenta el Ataque del bando del usuario." },
  "dragon-claw": { name: "Garra dragón", description: "Araña al objetivo con unas enormes garras afiladas." },
  "frenzy-plant": { name: "Planta feroz", description: "Golpea con una enorme planta. El usuario deberá descansar en el siguiente turno." },
  "bulk-up": { name: "Corpulencia", description: "Robustece el cuerpo para aumentar el Ataque y la Defensa." },
  "bounce": { name: "Rebote", description: "El usuario bota en el primer turno y golpea en el segundo. Puede paralizar al objetivo." },
  "mud-shot": { name: "Disparo de lodo", description: "El usuario ataca lanzando una bola de lodo al objetivo que también reduce su Velocidad." },
  "poison-tail": { name: "Cola venenosa", description: "Propina un golpe con la cola que puede envenenar al objetivo. Suele asestar un golpe crítico." },
  "creeping-chill": { name: "Congelación progresiva", description: "Ataque que puede congelar al objetivo." },
  "grass-knot": { name: "Nudo de pasto", description: "Enreda al objetivo con hierba y lo derriba. Cuanto más pesado es el objetivo, más potencia tiene el movimiento." },
  "chilling-water": { name: "Agua helada", description: "Chorro de agua helada que reduce la Velocidad del objetivo." },
  "water-sport": { name: "Chapoteo de agua", description: "El usuario se empapa en agua, lo que debilita los movimientos de tipo Fuego durante cinco turnos." },
  "calm-mind": { name: "Paz mental", description: "Mejora la concentración y calma el espíritu para aumentar el Ataque Especial y la Defensa Especial." },
  "leaf-blade": { name: "Hoja aguda", description: "Acuchilla con una hoja fina. Suele asestar un golpe crítico." },
  "dragon-dance": { name: "Danza de dragón", description: "Frenética danza mística que aumenta el Ataque y la Velocidad." },
  "rock-blast": { name: "Pedrada", description: "Lanza pedruscos al objetivo de dos a cinco veces seguidas." },
  "shock-wave": { name: "Onda de choque", description: "Ataque eléctrico muy rápido que no falla nunca." },
  "water-pulse": { name: "Pulso de agua", description: "Ataca con una potente onda de agua. Puede confundir al objetivo." },
  "doom-desire": { name: "Deseo final", description: "Ataca al objetivo con innumerables haces de luz dos turnos después de haber usado el movimiento." },
  "psycho-boost": { name: "Psicoimpulso", description: "Ataca al objetivo con toda su fuerza, pero reduce mucho el Ataque Especial del usuario." },
  "roost": { name: "Respiro", description: "Aterriza sobre la superficie para descansar. Restaura hasta la mitad de sus PS máximos." },
  "gravity": { name: "Gravedad", description: "Durante cinco turnos, se anulan los movimientos que alzan el vuelo y los Pokémon de tipo Volador o que levitan son vulnerables a movimientos de tipo Tierra." },
  "miracle-eye": { name: "Gran ojo", description: "Permite atacar con cualquier movimiento a objetivos de tipo Siniestro y golpear a Pokémon evasivos." },
  "wake-up-slap": { name: "Despabilador", description: "Inflige gran daño a objetivos dormidos. Sin embargo, los bofetones también los despiertan." },
  "hammer-arm": { name: "Brazo martillo", description: "Propina un golpe devastador con el puño, pero reduce la Velocidad del usuario." },
  "gyro-ball": { name: "Giro bola", description: "Embiste al objetivo con un potente ataque giratorio. Cuanto menor es la Velocidad del usuario respecto a la del objetivo, más daño causa." },
  "healing-wish": { name: "Deseo sanador", description: "El usuario se debilita, pero cura los problemas de estado del Pokémon que lo sustituye y restaura sus PS." },
  "brine": { name: "Salmuera", description: "Ataque con agua salada que causa el doble de daño si el objetivo ha perdido PS." },
  "natural-gift": { name: "Obsequio natural", description: "Lanza un ataque que varía según la baya que lleve el usuario." },
  "feint": { name: "Ataque sorpresa", description: "Destruye movimientos que protegen como Protección y Detección, dañando al objetivo." },
  "pluck": { name: "Picoteo", description: "Picotea al objetivo. Si este sostiene una baya, la picotea también y obtiene sus efectos." },
  "tailwind": { name: "Viento afín", description: "Crea un fuerte remolino que aumenta la Velocidad del bando del usuario durante cuatro turnos." },
  "acupressure": { name: "Acupresión", description: "Aplica presión en puntos clave del cuerpo para aumentar mucho una característica al azar." },
  "metal-burst": { name: "Explosión metálica", description: "Devuelve al rival el último ataque recibido, pero con mucha más fuerza." },
  "u-turn": { name: "Ida y vuelta", description: "Tras atacar, el usuario vuelve a toda prisa para dar paso a otro Pokémon del equipo." },
  "close-combat": { name: "Cuerpo a cuerpo", description: "Ataca ferozmente al objetivo sin protegerse, lo cual reduce la Defensa y la Defensa Especial del usuario." },
  "payback": { name: "Revancha", description: "El usuario contraataca con el doble de potencia si el objetivo usa un movimiento antes." },
  "assurance": { name: "Garantía", description: "Si el objetivo ya ha sufrido daño en ese turno, la potencia del movimiento se duplica." },
  "embargo": { name: "Embargo", description: "Impide al objetivo usar el objeto que lleva durante cinco turnos. Su Entrenador tampoco puede usar objetos con él." },
  "fling": { name: "Lanzamiento", description: "El usuario lanza contra el objetivo el objeto que lleva. La potencia del movimiento y su efecto varían según el objeto." },
  "psycho-shift": { name: "Psicocambio", description: "Usa su poder mental para transferir al objetivo sus problemas de estado." },
  "trump-card": { name: "As oculto", description: "Cuantos menos PP tenga el movimiento, mayor será la fuerza para atacar." },
  "heal-block": { name: "Anticuración", description: "Impide al objetivo usar movimientos, habilidades y objetos equipados que recuperan PS durante cinco turnos." },
  "wring-out": { name: "Apretón", description: "Estruja con fuerza al objetivo. Cuantos más PS tenga el objetivo, más fuerza tendrá el ataque." },
  "power-trick": { name: "Truco fuerza", description: "El usuario emplea su poder mental para intercambiar su Ataque y su Defensa." },
  "gastro-acid": { name: "Ácido gástrico", description: "El usuario arroja sus jugos biliares al objetivo, lo que anula el efecto de la habilidad en uso." },
  "lucky-chant": { name: "Cántico suerte", description: "Lanza al cielo un conjuro que protege a todo su equipo de golpes críticos." },
  "me-first": { name: "Yo primero", description: "Se adelanta al movimiento que pretende usar el objetivo y lo lanza antes con más fuerza. Si el usuario es más lento, falla." },
  "copycat": { name: "Copión", description: "Imita el movimiento usado justo antes. El movimiento falla si no se ha usado aún ninguno." },
  "power-swap": { name: "Cambiafuerza", description: "El usuario emplea su poder mental para intercambiar los cambios en el Ataque y el Ataque Especial con el objetivo." },
  "guard-swap": { name: "Cambiadefensa", description: "El usuario emplea su poder mental para intercambiar los cambios en la Defensa y la Defensa Especial con el objetivo." },
  "punishment": { name: "Castigo", description: "La fuerza del ataque aumenta cuanto más se ha fortalecido el objetivo con cambios de características." },
  "last-resort": { name: "Último recurso", description: "Este movimiento solo puede utilizarse tras haber usado al menos una vez todos los demás conocidos por el Pokémon." },
  "worry-seed": { name: "Abatidoras", description: "Planta una semilla en el objetivo que le causa pesar. Sustituye la habilidad del objetivo por Insomnio y le impide dormirse." },
  "sucker-punch": { name: "Golpe bajo", description: "Permite atacar con prioridad. Falla si el objetivo no está preparando ningún ataque." },
  "toxic-spikes": { name: "Púas tóxicas", description: "Lanza una trampa de púas tóxicas a los pies del objetivo que envenena a los rivales que entran en combate." },
  "heart-swap": { name: "Cambiaalmas", description: "Usa la fuerza mental para intercambiar con el objetivo los cambios en las características." },
  "aqua-ring": { name: "Anillo agua", description: "Crea un anillo de agua que rodea al usuario y restaura sus PS en cada turno durante cinco turnos." },
  "sheer-force": { name: "Poder brutal", description: "Mejora la potencia de los movimientos con efectos secundarios, pero anula dichos efectos." },
  "force-palm": { name: "Fuerza de palma", description: "Ataca al objetivo con una onda de choque y puede llegar a paralizarlo." },
  "aura-sphere": { name: "Aura esfera", description: "Libera una inmensa descarga de aura desde su interior. No falla nunca." },
  "rock-polish": { name: "Pulimento", description: "Pule su cuerpo para reducir la resistencia al aire y aumentar mucho su Velocidad." },
  "poison-jab": { name: "Púa veneno", description: "Ataca con una púa venenosa que puede envenenar al objetivo." },
  "dark-pulse": { name: "Pulso siniestro", description: "Onda de energía siniestra que puede hacer que el objetivo se amedrente." },
  "night-slash": { name: "Corte nocturno", description: "Corte rápido por la noche. Suele asestar un golpe crítico." },
  "aqua-tail": { name: "Cola acuática", description: "Azota al objetivo con la cola llena de agua y ataca con potencia bruta." },
  "x-scissor": { name: "Tijera X", description: "Cruza las guadañas o las garras para atacar al objetivo como si fueran unas tijeras." },
  "bug-buzz": { name: "Zumbido", description: "El usuario crea una onda sónica dañina moviendo su cuerpo que también puede reducir la Defensa Especial del objetivo." },
  "dragon-pulse": { name: "Pulso dragón", description: "Abre mucho la boca y libera una onda de choque con la que ataca al objetivo." },
  "dragon-rush": { name: "Carga dragón", description: "Ataca de forma brutal mientras intimida al objetivo. Puede amedrentarlo." },
  "power-gem": { name: "Joya de luz", description: "Ataca con un rayo de luz que centellea como si lo formaran miles de joyas." },
  "drain-punch": { name: "Puño drenador", description: "Un golpe que drena energía. El usuario recupera la mitad de los PS arrebatados al objetivo." },
  "vacuum-wave": { name: "Onda vacío", description: "Onda de energía que golpea al objetivo. Siempre ataca el primero." },
  "focus-blast": { name: "Explosión focal", description: "Descarga potente de poder concentrado que puede reducir la Defensa Especial del objetivo." },
  "brave-bird": { name: "Ave brava", description: "Pliega las alas y ataca con un vuelo rasante. El usuario se hiere seriamente a sí mismo." },
  "earth-power": { name: "Poder terrestre", description: "La tierra a los pies del objetivo erupciona violentamente. Puede reducir la Defensa Especial del objetivo." },
  "switcheroo": { name: "Trueque", description: "Intercambia con el objetivo los objetos que llevan tan rápido que es imposible verlo a simple vista." },
  "giga-impact": { name: "Gigaimpacto", description: "El usuario carga contra el objetivo con toda la fuerza que tiene y descansa en el siguiente turno." },
  "nasty-plot": { name: "Maquinación", description: "Estimula su cerebro pensando en cosas malas. Aumenta mucho el Ataque Especial." },
  "bullet-punch": { name: "Puño bala", description: "Ataca con fuertes puñetazos tan rápidos como proyectiles. Este movimiento tiene prioridad alta." },
  "avalanche": { name: "Alud", description: "Ataque que produce el doble de daño si el usuario resulta herido en el mismo turno." },
  "ice-shard": { name: "Esquirla helada", description: "Lanza una esquirla de hielo al objetivo. Este movimiento tiene prioridad alta." },
  "shadow-sneak": { name: "Sombra vil", description: "Extiende su sombra y ataca al objetivo por la espalda. Este movimiento tiene prioridad alta." },
  "mud-bomb": { name: "Bomba fango", description: "Ataca lanzando una compacta bola de fango. Puede bajar la Precisión del objetivo." },
  "psycho-cut": { name: "Psicocorte", description: "Ataca al objetivo con cuchillas formadas por energía psíquica. Suele asestar un golpe crítico." },
  "zen-headbutt": { name: "Cabezazo zen", description: "Concentra su energía psíquica en la cabeza para golpear. Puede hacer que el objetivo se amedrente." },
  "mirror-shot": { name: "Disparo espejo", description: "El usuario libera un haz de energía desde su pulido cuerpo. Puede bajar la Precisión." },
  "flash-cannon": { name: "Cañón resplandor", description: "El usuario concentra toda la luz del cuerpo y la libera. Puede reducir la Defensa Especial del objetivo." },
  "rock-climb": { name: "Treparrocas", description: "Ataca con una gran embestida. Puede confundir al objetivo." },
  "defog": { name: "Desempañar", description: "Potente viento que barre los efectos de movimientos como Reflejo o Pantalla de Luz usados por el objetivo. También reduce su Evasión." },
  "trick-room": { name: "Espacio raro", description: "Crea un espacio misterioso en el que los Pokémon lentos se mueven primero durante cinco turnos." },
  "acrobatics": { name: "Acrobacias", description: "Realiza acrobacias aéreas que pueden amedrentar al objetivo. La potencia aumenta si el usuario no lleva objeto." },
  "cross-poison": { name: "Veneno X", description: "Tajo que puede envenenar al objetivo. Suele asestar un golpe crítico." },
  "gunk-shot": { name: "Lanzamugre", description: "Lanza contra el objetivo basura asquerosa y puede envenenarlo." },
  "iron-head": { name: "Cabeza de hierro", description: "Ataca con su cabeza dura como el hierro. Puede hacer que el objetivo se amedrente." },
  "magnet-bomb": { name: "Magnetobomba", description: "Lanza unas bombas de hierro que se pegan al adversario. No se puede esquivar." },
  "stone-edge": { name: "Roca afilada", description: "Clava piedras muy afiladas al objetivo. Suele asestar un golpe crítico." },
  "captivate": { name: "Seducción", description: "Si el objetivo es del sexo opuesto, queda embelesado y baja mucho su Ataque Especial." },
  "stealth-rock": { name: "Trampa de rocas", description: "Hace flotar innumerables rocas alrededor del objetivo que hieren a los rivales que entran en combate." },
  "grass-knot": { name: "Nudo de pasto", description: "Enreda al objetivo con hierba y lo derriba. Cuanto más pesado es el objetivo, más potencia tiene el movimiento." },
  "chatter": { name: "Parloteo", description: "Ataca con una onda de sonido muy ruidosa compuesta por palabras y confunde al objetivo." },
  "judgment": { name: "Juicio final", description: "Emite incontables haces de luz. El tipo del movimiento varía según la tabla que lleve el usuario." },
  "bug-bite": { name: "Picadura", description: "Pica al objetivo. Si el objetivo lleva una baya, el usuario se la come y se beneficia de su efecto." },
  "charge-beam": { name: "Rayo carga", description: "Lanza un rayo eléctrico contra el objetivo. Puede aumentar el Ataque Especial del usuario." },
  "wood-hammer": { name: "Mazo", description: "Golpea al objetivo con un tronco. El usuario se hiere ligeramente a sí mismo." },
  "aqua-jet": { name: "Chorro acuático", description: "Ataque acuático de velocidad extrema. Este movimiento tiene prioridad alta." },
  "attack-order": { name: "A atacar", description: "El usuario llama a sus súbditos para que ataquen. Suele asestar un golpe crítico." },
  "defend-order": { name: "A defender", description: "El usuario llama a sus súbditos para que formen un escudo viviente. Aumenta la Defensa y la Defensa Especial." },
  "heal-order": { name: "Auxilio", description: "El usuario llama a sus súbditos para que lo curen. Recupera hasta la mitad de los PS máximos." },
  "head-smash": { name: "Topetazo", description: "El usuario arriesga su vida y lanza un cabezazo con toda su fuerza, pero también se hiere gravemente a sí mismo." },
  "double-hit": { name: "Doble golpe", description: "Golpea al objetivo dos veces seguidas con la cola u otras partes de su cuerpo." },
  "roar-of-time": { name: "Rugido temporal", description: "Ataca al objetivo usando tal energía que el tiempo se distorsiona. El usuario deberá descansar en el siguiente turno." },
  "spacial-rend": { name: "Corte espacial", description: "Desgarra al objetivo y el espacio a su alrededor. Suele asestar un golpe crítico." },
  "lunar-dance": { name: "Danza lunar", description: "Hermosa danza que revitaliza el cuerpo del usuario, cura sus problemas de estado y lo prepara para el siguiente Pokémon." },
  "crush-grip": { name: "Agarre", description: "Ataque que causa más daño cuantos más PS le queden al objetivo." },
  "dark-void": { name: "Abismo negro", description: "El objetivo es enviado a un mundo de tinieblas que lo hace dormir." },
  "seed-flare": { name: "Fulgor semilla", description: "El usuario libera una onda de choque de su cuerpo. Puede reducir mucho la Defensa Especial del objetivo." },
  "ominous-wind": { name: "Viento ominoso", description: "Produce un viento horripilante. Puede subir de golpe todas las características del usuario." },
  "shadow-force": { name: "Golpe umbrío", description: "En el primer turno, desaparece. En el segundo, golpea al objetivo aunque se esté protegiendo." },
  "hone-claws": { name: "Afilagarras", description: "El usuario se afila las garras para aumentar su Ataque y su Precisión." },
  "wide-guard": { name: "Guardia amplia", description: "Bloquea los ataques de objetivo múltiple lanzados contra el bando del usuario durante un turno." },
  "guard-split": { name: "Guardia dividida", description: "El usuario emplea sus poderes para hacer la media de su Defensa y su Defensa Especial con las del objetivo y compartirlas." },
  "power-split": { name: "Fuerza dividida", description: "El usuario emplea sus poderes para hacer la media de su Ataque y su Ataque Especial con los del objetivo y compartirlos." },
  "wonder-room": { name: "Zona extraña", description: "Crea un espacio misterioso donde se intercambian la Defensa y la Defensa Especial de todos los Pokémon durante cinco turnos." },
  "psyshock": { name: "Psicochoque", description: "Ataque psíquico que compara la Defensa física del objetivo con el Ataque Especial del usuario." },
  "rage-powder": { name: "Polvo ira", description: "Usa un polvo que enerva a los rivales y hace que centren en el usuario su atención y sus movimientos." },
  "telekinesis": { name: "Telequinesis", description: "El usuario emplea su poder mental para hacer flotar al objetivo, y lo convierte en un blanco fácil durante tres turnos." },
  "magic-room": { name: "Zona mágica", description: "Crea un espacio misterioso que inutiliza todos los objetos de los Pokémon durante cinco turnos." },
  "smack-down": { name: "Antiaéreo", description: "Ataca lanzando una piedra o un proyectil. Si el objetivo está en el aire, lo estrella contra el suelo." },
  "storm-throw": { name: "Llave tempestad", description: "Lanza un golpe devastador. Siempre asesta un golpe crítico." },
  "flame-burst": { name: "Golpe de fuego", description: "Golpea al objetivo con una llamarada que afecta también a los Pokémon adyacentes." },
  "sludge-wave": { name: "Onda de lodo", description: "Una onda tóxica que daña a los Pokémon adyacentes. Puede envenenar." },
  "quiver-dance": { name: "Danza del aleteo", description: "Danza mística que aumenta el Ataque Especial, la Defensa Especial y la Velocidad." },
  "heavy-slam": { name: "Golpe pesado", description: "El usuario golpea con todo su cuerpo. Cuanto mayor sea su peso comparado con el del objetivo, mayor será la potencia del movimiento." },
  "synchronoise": { name: "Sincronía", description: "Ataca con una onda de energía psíquica. Solo afecta a Pokémon del mismo tipo que el usuario." },
  "electro-ball": { name: "Balón eléctrico", description: "Lanza una bola de electricidad. Cuanto más lento es el objetivo respecto al usuario, más potencia tiene el movimiento." },
  "soak": { name: "Empapar", description: "Empapad al objetivo con agua, convirtiéndolo en Pokémon de tipo Agua." },
  "flame-charge": { name: "Carga de fuego", description: "Llamas que golpean al objetivo y aumentan la Velocidad del usuario." },
  "coil": { name: "Enrosque", description: "El usuario se concentra, lo que le permite aumentar su Ataque, su Defensa y su Precisión." },
  "low-sweep": { name: "Barredora", description: "Ataque rápido dirigido a los pies del objetivo que le hace perder Velocidad." },
  "acid-spray": { name: "Bomba ácida", description: "Ataca con un líquido corrosivo que reduce mucho la Defensa Especial del objetivo." },
  "foul-play": { name: "Juego sucio", description: "El usuario emplea la fuerza del objetivo para atacarlo. Cuanto mayor es el Ataque del objetivo, más daño provoca." },
  "simple-beam": { name: "Onda simple", description: "Lanza una onda psíquica que hace que la habilidad del objetivo pase a ser Simple." },
  "entrainment": { name: "Danza amiga", description: "Una extraña danza que induce al objetivo a imitarla y cambia su habilidad por la misma que la del usuario." },
  "after-you": { name: "Ceda el paso", description: "Si el usuario es el más rápido, permite al objetivo usar un movimiento justo tras él, adelantándose a Pokémon más rápidos." },
  "round": { name: "Canon", description: "Entona una canción que daña al objetivo. Si otro Pokémon lo usa en el mismo turno, ataca justo a continuación y la potencia del movimiento aumenta." },
  "echoed-voice": { name: "Eco voz", description: "Un susurro que aumenta de potencia conforme el usuario y otros Pokémon lo van utilizando." },
  "chip-away": { name: "Guardia baja", description: "Un ataque que busca los puntos débiles del objetivo y puede causarle daño aunque cambien sus características." },
  "clear-smog": { name: "Humo claro", description: "Ataca al objetivo con una singular bola de lodo que elimina cualquier cambio en sus características." },
  "stored-power": { name: "Poder acumulado", description: "Acumula poder para golpear. Cuanto más suban las características del usuario, mayor será la potencia del movimiento." },
  "quick-guard": { name: "Guardia rápida", description: "Bloquea movimientos de prioridad alta lanzados contra el usuario y sus aliados durante un turno." },
  "ally-switch": { name: "Cambio aliado", description: "El usuario intercambia posiciones con un aliado de forma instantánea." },
  "scald": { name: "Escaldadura", description: "Ataque con agua hirviendo que puede causar quemaduras." },
  "shell-smash": { name: "Rompecoraza", description: "El usuario rompe su coraza y reduce su Defensa y su Defensa Especial, pero aumenta mucho su Ataque, su Ataque Especial y su Velocidad." },
  "heal-pulse": { name: "Pulso sanador", description: "Una onda curativa restaura la mitad de los PS máximos del objetivo." },
  "hex": { name: "Infortunio", description: "Ataque que causa un gran daño a los objetivos que sufren problemas de estado." },
  "sky-drop": { name: "Caída libre", description: "Primer turno: lanza al objetivo al aire. Segundo turno: lo hace caer. Mientras está en el aire, no lo deja moverse." },
  "shift-gear": { name: "Cambio de marcha", description: "Al hacer girar los engranajes, el usuario aumenta su Ataque y aumenta mucho su Velocidad." },
  "circle-throw": { name: "Llave giro", description: "Lanza por los aires al objetivo y hace que salga otro Pokémon. Si es uno salvaje, acaba el combate." },
  "incinerate": { name: "Incineración", description: "Ataque incendiario que destruye los objetos que llevan los objetivos, además de causar daño." },
  "quash": { name: "Sometimiento", description: "Somete al objetivo para hacer que se mueva después en el turno actual." },
  "acrobatics": { name: "Acrobacias", description: "Realiza acrobacias aéreas que pueden amedrentar al objetivo. La potencia aumenta si el usuario no lleva objeto." },
  "reflect-type": { name: "Clonatipo", description: "Cambia el tipo del usuario al mismo tipo que el del objetivo." },
  "retaliate": { name: "Represalia", description: "Venga a los aliados caídos. Si en el turno anterior han derrotado a alguno, la potencia del movimiento aumentará." },
  "final-gambit": { name: "Sacrificio Final", description: "El usuario se sacrifica causándole un daño al objetivo equivalente a sus propios PS perdidos." },
  "bestow": { name: "Ofrenda", description: "Entrega el objeto que lleva al objetivo en caso de que este no tenga ninguno." },
  "inferno": { name: "Infierno", description: "Ataque abrasador que causa quemaduras al objetivo." },
  "water-pledge": { name: "Compromiso agua", description: "Ataque que puede combinarse con otros movimientos y crear efectos especiales." },
  "fire-pledge": { name: "Compromiso fuego", description: "Ataque que puede combinarse con otros movimientos y crear efectos especiales." },
  "grass-pledge": { name: "Compromiso planta", description: "Ataque que puede combinarse con otros movimientos y crear efectos especiales." },
  "volt-switch": { name: "Cambio voltio", description: "El usuario ataca y vuelve a toda prisa para dar paso a otro Pokémon del equipo." },
  "struggle-bug": { name: "Lucha bicho", description: "Lucha frenética que puede reducir la Defensa Especial del objetivo." },
  "bulldoze": { name: "Terratemblor", description: "Sacudida sísmica que afecta a los Pokémon adyacentes y también reduce su Velocidad." },
  "frost-breath": { name: "Vaho helado", description: "El usuario ataca expulsando un aliento gélido. Siempre asesta un golpe crítico." },
  "dragon-tail": { name: "Cola de dragón", description: "Ataca al objetivo y lo obliga a cambiarse por otro Pokémon. Si es uno salvaje, acaba el combate." },
  "work-up": { name: "Avivar", description: "El usuario se concentra y aumenta su Ataque y su Ataque Especial." },
  "electroweb": { name: "Electrotela", description: "Atrapa y ataca al objetivo con una telaraña eléctrica. También reduce su Velocidad." },
  "wild-charge": { name: "Carga salvaje", description: "El usuario se envuelve de electricidad y carga contra el objetivo, pero también se hiere ligeramente a sí mismo." },
  "drill-run": { name: "Taladradora", description: "El usuario golpea usando su cuerpo como un taladro. Suele asestar un golpe crítico." },
  "dual-chop": { name: "Golpe dual", description: "Golpea dos veces seguidas con las partes más recias de su cuerpo." },
  "heart-stamp": { name: "Sello de corazón", description: "El usuario despista al objetivo con gestos adorables y aprovecha la ocasión para asestarle un golpe tremendo que puede hacerlo retroceder." },
  "horn-leech": { name: "Drenacuerno", description: "El usuario ensarta al objetivo con su cornamenta y absorbe su energía. El Pokémon recupera la mitad de los PS arrebatados al objetivo." },
  "sacred-sword": { name: "Espada sagrada", description: "El usuario ataca con una espada, ignorando cualquier cambio en las características del objetivo." },
  "razor-shell": { name: "Coraza afilada", description: "Ataca con una afilada vieira al objetivo y puede reducir su Defensa." },
  "heat-crash": { name: "Golpe de calor", description: "El usuario ataca con su cuerpo ardiente. Cuanto mayor sea su peso comparado con el del objetivo, mayor será la potencia del movimiento." },
  "leaf-tornado": { name: "Ciclón de hojas", description: "Tritura con afiladas hojas y puede bajar la Precisión del objetivo." },
  "steamroller": { name: "Aplanadora", description: "El usuario se hace una bola y arrolla al objetivo con su cuerpo. Puede hacerlo retroceder." },
  "cotton-guard": { name: "Guardialgodón", description: "Cubre al Pokémon con una madeja protectora. Aumenta muchísimo la Defensa." },
  "night-daze": { name: "Rayo nocturno", description: "Ataque con una onda siniestra que puede reducir la Precisión del objetivo." },
  "psystrike": { name: "Psistrike", description: "Ataque psíquico que compara la Defensa Especial del objetivo con el Ataque Especial del usuario." },
  "tail-slap": { name: "Azotagolpes", description: "Golpea al objetivo múltiples veces con la cola de dos a cinco veces seguidas." },
  "hurricane": { name: "Huracán", description: "Potente vendaval que puede confundir al objetivo." },
  "head-charge": { name: "Carga de cabeza", description: "Propina un tremendo cabezazo. El usuario se hiere ligeramente a sí mismo." },
  "gear-grind": { name: "Rueda doble", description: "Arroja dos engranajes de hierro sobre el objetivo. Golpea dos veces seguidas." },
  "searing-shot": { name: "Bomba ígnea", description: "Un infierno de llamas daña a los Pokémon adyacentes en combate. Puede causar quemaduras." },
  "techno-blast": { name: "Tecno shock", description: "Ataca al objetivo con un gran láser. El tipo del ataque lo determina el cartucho que porta el usuario." },
  "relic-song": { name: "Canto arcaico", description: "Ataca conmoviendo al objetivo con un antiguo canto. Puede dormirlo." },
  "secret-sword": { name: "Espada secreta", description: "Ensarta al objetivo con un largo cuerno dotado de un poder místico que provoca daño físico." },
  "glaciate": { name: "Mundo gélido", description: "Ataque con aire helado que reduce la Velocidad del objetivo." },
  "bolt-strike": { name: "Ataque fulgor", description: "Ataca envolviéndose de una gran carga eléctrica y embistiendo al objetivo con ella. Puede paralizar." },
  "blue-flare": { name: "Llama azul", description: "Ataca con una bella pero potente llama azul que rodea al objetivo. Puede causar quemaduras." },
  "fiery-dance": { name: "Danza de fuego", description: "Danza de fuego que puede aumentar el Ataque Especial del usuario." },
  "snarl": { name: "Alarido", description: "Chillido desagradable que reduce el Ataque Especial del objetivo." },
  "icicle-crash": { name: "Carámbano", description: "Lanza grandes carámbanos. Puede amedrentar al objetivo." },
  "v-create": { name: "V de fuego", description: "De su frente mana una ardiente llama con la que se arroja contra el objetivo. Reduce la Defensa, la Defensa Especial y la Velocidad del usuario." },
  "fusion-flare": { name: "Llama fusión", description: "Ataque con una llama ardiente que es más potente si el usuario es del tipo Fuego." },
  "fusion-bolt": { name: "Rayo fusión", description: "Ataque con un rayo que es más potente si el usuario es del tipo Eléctrico." },
  "mat-block": { name: "Escudo tatami", description: "El usuario usa un tatami para escudarse de los ataques enemigos. Protege también a los aliados. No funciona contra movimientos de estado." },
  "belch": { name: "Eructo", description: "El usuario causa daño a su objetivo lanzándole un eructo. Para poder utilizar este movimiento, tiene que haberse comido una baya equipada." },
  "rototiller": { name: "Fertilizante", description: "Labra la tierra haciendo que sea más fácil cultivarla y consigue que aumente el Ataque y el Ataque Especial de los Pokémon de tipo Planta." },
  "sticky-web": { name: "Red pegajosa", description: "Coloca una red pegajosa alrededor del objetivo que reduce la Velocidad de los rivales que entran en combate." },
  "fell-stinger": { name: "Aguijón letal", description: "Si se derrota al objetivo utilizando este movimiento, aumenta muchísimo el Ataque del usuario." },
  "phantom-force": { name: "Golpe fantasma", description: "El usuario desaparece en el primer turno y ataca a su objetivo en el segundo. Permite acertar aunque el objetivo esté protegiéndose." },
  "trick-or-treat": { name: "Halloween", description: "Invita al objetivo a celebrar Halloween, lo que añade el tipo Fantasma a los tipos de este." },
  "noble-roar": { name: "Rugido de guerra", description: "Intimida a su objetivo con un rugido de guerra, lo que reduce tanto su Ataque como su Ataque Especial." },
  "ion-deluge": { name: "Cortina plasma", description: "El Pokémon disemina partículas con carga eléctrica que convierten los movimientos de tipo Normal en tipo Eléctrico." },
  "parabolic-charge": { name: "Carga parabólica", description: "Inflige daño a los Pokémon adyacentes. El usuario absorbe la mitad del daño producido para restaurar sus propios PS." },
  "forest-curse": { name: "Condena silvana", description: "El objetivo es presa de la maldición del bosque, por lo que pasa a ser un Pokémon de tipo Planta, además de conservar sus tipos habituales." },
  "petal-blizzard": { name: "Tormenta pétalos", description: "El usuario desata un intenso vendaval de pétalos que daña a los Pokémon adyacentes." },
  "freeze-dry": { name: "Liofilización", description: "Enfría súbitamente al objetivo e incluso puede congelarlo. Es supereficaz contra Pokémon de tipo Agua." },
  "disarming-voice": { name: "Voz encantadora", description: "Obnubila al objetivo con su fascinante voz y le provoca daños emocionales. No falla nunca." },
  "parting-shot": { name: "Última palabra", description: "El usuario se cambia por otro Pokémon del equipo, pero antes intimida al objetivo y reduce su Ataque y su Ataque Especial." },
  "topsy-turvy": { name: "Reversión", description: "Invierte por completo los cambios en las características del objetivo." },
  "draining-kiss": { name: "Beso drenador", description: "El usuario absorbe energía del objetivo con un beso y restaura sus propios PS en una cantidad igual o superior a la mitad del daño infligido." },
  "crafty-shield": { name: "Truco defensa", description: "Usa unos misteriosos poderes para protegerse a sí mismo y a sus aliados de movimientos de estado, pero no de otro tipo de ataques." },
  "flower-shield": { name: "Defensa floral", description: "Aumenta la Defensa de todos los Pokémon de tipo Planta que hay en el combate usando unos misteriosos poderes." },
  "grassy-terrain": { name: "Campo de hierba", description: "Durante cinco turnos, se potencian los movimientos de tipo Planta y los Pokémon que están en contacto con el suelo recuperan PS en cada turno." },
  "misty-terrain": { name: "Campo de niebla", description: "Durante cinco turnos, los Pokémon que están en el suelo no sufren problemas de estado y se reduce a la mitad el daño de los movimientos de tipo Dragón." },
  "electrify": { name: "Electrificación", description: "Si el objetivo queda electrificado antes de usar un movimiento, este será de tipo Eléctrico." },
  "play-rough": { name: "Juego rudo", description: "El usuario le hace cucamonas al objetivo y lo ataca. Puede reducir el Ataque del objetivo." },
  "fairy-wind": { name: "Viento feérico", description: "El usuario desata un vendaval feérico que arremete contra el objetivo." },
  "moonblast": { name: "Explosión lunar", description: "Ataque explosivo que puede reducir el Ataque Especial del objetivo." },
  "boomburst": { name: "Estruendo", description: "Explosión sónica que daña a todos los Pokémon adyacentes." },
  "fairy-lock": { name: "Cierre feérico", description: "El usuario encierra a todos los Pokémon en el terreno de combate con poder feérico, impidiendo que alguien abandone el campo." },
  "kings-shield": { name: "Escudo real", description: "El usuario adopta una postura defensiva y se protege de cualquier daño. Reduce el Ataque de cualquier Pokémon con el que entre en contacto." },
  "play-nice": { name: "Camaradería", description: "Se hace amigo de su objetivo y consigue que a este se le quiten las ganas de combatir, lo que reduce su Ataque." },
  "confide": { name: "Confidencia", description: "Hace que el objetivo pierda la concentración contándole un secreto y reduce su Ataque Especial." },
  "diamond-storm": { name: "Tormenta de diamantes", description: "Desata un devastador vendaval de diamantes para dañar al objetivo. Puede aumentar mucho la Defensa del usuario." },
  "steam-eruption": { name: "Chorro de vapor", description: "Envuelve al objetivo con vapor extremadamente caliente que puede causar quemaduras." },
  "hyperspace-hole": { name: "Paso dimensional", description: "El usuario aparece junto al objetivo usando un agujero dimensional y le asesta un golpe que movimientos como Protección o Detección no pueden evitar." },
  "water-shuriken": { name: "Shuriken agua", description: "Lanza un shuriken de agua que golpea al objetivo. Este movimiento tiene prioridad alta." },
  "mystical-fire": { name: "Fuego místico", description: "Ataque con un fuego místico que puede reducir el Ataque Especial del objetivo." },
  "spiky-shield": { name: "Escudo de púas", description: "Frena todos los ataques, pero puede fallar si se usa repetidamente. Hiere a quien use un movimiento de contacto." },
  "aromatic-mist": { name: "Niebla aromática", description: "Consigue aumentar la Defensa Especial de un aliado con una fragancia misteriosa." },
  "eerie-impulse": { name: "Onda anómala", description: "El usuario irradia unas raras ondas que, al alcanzar al objetivo, reducen mucho su Ataque Especial." },
  "venom-drench": { name: "Trampa venenosa", description: "Impregna a su objetivo con un líquido venenoso que disminuye el Ataque, el Ataque Especial y la Velocidad. Solo afecta a Pokémon ya envenenados." },
  "powder": { name: "Pólvora", description: "Esparce un polvo sobre el objetivo. Si este usa un movimiento de tipo Fuego en el mismo turno, el polvo explota y le inflige daño." },
  "geomancy": { name: "Geocontrol", description: "Concentra energía durante el primer turno, de forma que su Velocidad, su Ataque Especial y su Defensa Especial aumenten mucho en el segundo." },
  "magnetic-flux": { name: "Aura magnética", description: "Manipula el campo magnético y logra aumentar la Defensa y la Defensa Especial de los Pokémon aliados que cuenten con las habilidades Más o Menos." },
  "dazzling-gleam": { name: "Brillo feérico", description: "Emite un brillo deslumbrante de energía feérica. Ataca a los Pokémon adyacentes." },
  "cytosis": { name: "Multiplicación celular", description: "El usuario enseña al equipo de cómo multiplicar sus células para aumentar su Defensa y su Defensa Especial." },
  "origin-pulse": { name: "Pulso original", description: "Canaliza un poder primigenio para atacar al objetivo. Afecta a Pokémon adyacentes." },
  "precipice-blades": { name: "Filo del abismo", description: "Hace que el poder latente de la tierra se manifieste en forma de hojas afiladas y ataca al objetivo con ellas." },
  "dragon-ascent": { name: "Ascenso dracónico", description: "El usuario se precipita desde el cielo a una velocidad de vértigo para atacar al objetivo, pero reduce su Defensa y su Defensa Especial." },
  "hyperspace-fury": { name: "Cerco dimensión", description: "Ataca al objetivo con una ráfaga de golpes que pasan por alto los efectos de movimientos como Protección o Detención. Reduce la Defensa del usuario." },
  "oblivion-wing": { name: "Ala del olvido", description: "El usuario absorbe energía del objetivo y recupera PS en una cantidad igual o superior a la mitad del daño infligido." },
  "thousand-arrows": { name: "Mil flechas", description: "Acierta incluso a Pokémon que estén en el aire y los hace caer al suelo." },
  "thousand-waves": { name: "Mil temblores", description: "El usuario genera ondas sísmicas que se propagan por el suelo y sacuden al objetivo. Los Pokémon alcanzados no podrán huir del combate ni ser cambiados por otros." },
};
